background #222228
foreground #bbaaaa

# black
color0 #000000
color8 #444444

# red
color1 #dd2200
color9 #ff6633

# green
color2 #11bb11
color10 #00cc33

# yellow
color3 #cc6600
color11 #ff9900

# blue
color4 #1144dd
color12 #0099ff

# magenta
color5 #bb33bb
color13 #cc33ff

# cyan
color6 #66aadd
color14 #00ccff

# white
color7 #bbbbbb
color15 #ffffff
