# Signal to clipcopy that OSC 52 can be used
env OSC52=1

# Ctrl-Backspace -> Ctrl-W (backward-kill-word)
map ctrl+backspace send_text all \x17

# Cmd-Left/Right default to same as Alt-Left/Right, make them distinct
map cmd+left  send_text all \x1b[1;9D
map cmd+right send_text all \x1b[1;9C
